### ISSUE TITLE
Callback syntax documentation

### ISSUE THREAD

**Issue by eflukx** [Wattics/api-client-ruby#2]
Hi I was just reading your gem documentation (as we might be doing a Wattics integration soon! :smile:) and noticed something odd.

The documented callbacks follow this syntax: 

```ruby
agent.add_measurement_sent_handler do
  -> (measurement, response) {
    puts "#{response.code} - #{measurement}"
  }
end
```

i.e. a block enclosing another block (lambda). Is this a typo, does this work by accident or is it actually meant that the callback yields a lambda?

I would expect a syntax like this

```ruby
agent.add_measurement_sent_handler do |measurement, response|
  puts "#{response.code} - #{measurement}"
end
```

or maybe (less idiomatic imo):

```ruby
agent.add_measurement_sent_handler =
    -> (measurement, response) { puts "#{response.code} - #{measurement}" }
```

btw. Great to see you have a Ruby Gem available! Saves me some work :)

**Comment by jcouso** [comment]
Hi @eflukx!
First, thank you raising this issue! we are super happy you are doing an integration with us.  🙏🏻

Regarding you question, yes the idea here is that you can pass a block with lambda inside that handles the callback and yes, it works! The callback is asynchronous from the sending, and gets handle by a separate thread. We want to give out customers the freedom to code any function they see fit to their business logic and pass it to the callback thread. This gem was a port from other java lib that we initially developed, so maybe some idiomatic was carried. We will take this into consideration for next version of the gem to make it more idiomatically friendly.

Let me know if you have any other doubts or issues.

**Comment by eflukx** [comment]
Consider the following function

```ruby
def accepts_block
  yield "accepted!"
end
```

Typically function is called like this

```ruby
accepts_block { |v| "block #{v}" }
=> "block accepted!"
```

But _by default_ Ruby allows you to pass a lambda as well:

```ruby
lbd = ->(v){ "block #{v}" }
accepts_block &lbd

=> "block accepted!"
```
This approach would (imho!) be a more idiomatic approach.

Furthermore, I see some very serious hand crafted Thread handling in the Agent, Processor and ProcessorPool classes. Haven't studied the code very deeply yet, but seems overly complex. Maybe it's better to reach out for a specialized gem to do the Async/Parallel heavy-lifting?

**Comment by jcouso** [comment]
Hi, This gem was develop addressing all issue that we have seen our clients have when trying to connect to our API. The major issue is making sure measurements are posted in order, so although we have Async and Parallel gem, we needed a tailor solution to address all of our partners. We builded this considering people with less technical background. The rules to connect to our API are pretty straight forward. Here is a link to the doc for the api  [link](https://docs.wattics.com/2016/02/22/how-can-i-upload-data-via-the-wattics-rest-api/). Let me know if you need any other support for connecting to our backend.

**Comment by eflukx** [comment]
Hmmz.. I was just about to roll my own when I realized

>  measurements are posted in order,

That's indeed an interesting requirement, especially when combined when running async/parallel requests these kind of guarantees cannot be made. I see the Wattics API is mostly geared towards being a real-time streaming interface (with meters directly attached), and is not so much an interface catering "bulk write"-semantics. Having the (or a separate) API that allows writing multiple data points in one request (i.e. array of data) would certainly solve a big part of the problem (of bulk-writing historic data) and as such would be a great addition to the platform!

Anyway, I'll try out a couple of things and see what my mileage will be...

**Comment by eflukx** [comment]
Ok, let's close this issue, as we've wandered quite far off topic by now... 🍷
